- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
    network: default
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: 72602 Cluster
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- search:
    provider: google
    target: _blank
- logo:
    href: http://home.72602.online
    target: _blank 
    icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/port_icon.png
