apiVersion: v1
kind: ConfigMap
metadata:
  name: opencode-json-config
data:
  opencode.json: |
    {
      "$schema": "https://opencode.ai/config.json",
      "agent": {
        "72602-k3s-maintainer": {
          "options": {
            "store": false
          }
        },
        "hugo-doc-maintainer": {
          "options": {
            "store": false
          }
        }
      }
    }
