apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-docs
spec:
  project: default
  source:
    repoURL: 'https://github.com/AaronYang0628/docs.git'
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: application
