apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: charge-spot-quest
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: charge-spot
  source:
    repoURL: https://github.com/AaronYang0628/charge-spot-quest.git
    targetRevision: 317b44388ca5ad7a444164fe9cd98648a0c60014
    path: charts/charge-spot-quest
    helm:
      releaseName: charge-spot-quest
      values: |
        fullnameOverride: charge-spot-quest
        replicaCount: 1

        image:
          repository: ghcr.io/aaronyang0628/charge-spot-quest
          tag: "0.1.11"
          digest: sha256:f83c8919774e54c5eb86e5cdf002fddff58c8c6615fd86c37e7a724e654eb04d
          pullPolicy: IfNotPresent

        postgresql:
          enabled: false

        sqlite:
          enabled: true
          persistence:
            enabled: true
            size: 1Gi
            storageClass: local-path

        extraEnv:
          - name: DINGTALK_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: charge-spot-dingtalk
                key: webhook_url
          - name: DINGTALK_SEC_SECRET
            valueFrom:
              secretKeyRef:
                name: charge-spot-dingtalk
                key: sec_secret

        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 512Mi

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: lets-encrypt
            nginx.ingress.kubernetes.io/proxy-body-size: 5m
          hosts:
            - host: charge.72602.space
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: charge.72602.space-tls
              hosts:
                - charge.72602.space

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
