apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: charge-spot-quest
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: charge-spot
  source:
    repoURL: https://github.com/AaronYang0628/charge-spot-quest.git
    targetRevision: fb665412d09dfc57f6106f124adfc5665435e05c
    path: charts/charge-spot-quest
    helm:
      releaseName: charge-spot-quest
      values: |
        fullnameOverride: charge-spot-quest
        replicaCount: 1

        image:
          repository: ghcr.io/aaronyang0628/charge-spot-quest
          tag: "0.1.10"
          digest: sha256:36b8aa593506cff4da5500e7a323ad2fa6ce6cdce22212ebc6384e29a18ef268
          pullPolicy: IfNotPresent

        postgresql:
          enabled: false

        sqlite:
          enabled: true
          persistence:
            enabled: true
            size: 1Gi
            storageClass: local-path

        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 512Mi

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: lets-encrypt
            nginx.ingress.kubernetes.io/proxy-body-size: 5m
          hosts:
            - host: charge.72602.space
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: charge.72602.space-tls
              hosts:
                - charge.72602.space

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
