apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-docs-config
data:
  REPO_URL: https://github.com/AaronYang0628/docs.git
  PUBLISH_REVISION: caec70e16015cd5992ef4e567d51a3c001367091
  SITE_SOURCE_DIR: /src
  SITE_OUTPUT_DIR: /output
  SITE_BASE_URL: https://ops.docs.72602.space
