apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-docs-config
data:
  REPO_URL: https://github.com/AaronYang0628/docs.git
  REPO_BRANCH: main
  SITE_SOURCE_DIR: /src
  SITE_OUTPUT_DIR: /output
  SITE_BASE_URL: https://port.72602.online
