apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  source:
    repoURL: https://github.com/AaronYang0628/docs.git
    targetRevision: main
    path: manifests/ops-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
