apiVersion: v1
kind: Secret
metadata:
  name: helm-chart-mirror-sub2api-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: helm-chart-mirror-sub2api-oci
  type: helm
  enableOCI: "true"
  url: ghcr.io/aaronyang0628/helm-chart-mirror
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sub2api
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: sub2api
      namespace: application
      jsonPointers:
        - /spec/template/spec/priorityClassName
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: ghcr.io/aaronyang0628/helm-chart-mirror
    chart: sub2api
    targetRevision: 0.1.12
    helm:
      values: |
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1

        ingress:
          enabled: false

        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 2Gi

        sub2api:
          auth:
            existingSecret: sub2api-auth

        extraEnvVars:
          - name: HTTP_PROXY
            value: http://192.168.0.25:17890
          - name: HTTPS_PROXY
            value: http://192.168.0.25:17890
          - name: NO_PROXY
            value: 127.0.0.1,localhost,.svc,.cluster.local,10.42.0.0/16,10.43.0.0/16,192.168.0.25

        redis:
          auth:
            existingSecret: sub2api-redis
            existingSecretPasswordKey: redis-password

        postgresql:
          enabled: false

        externalPostgresql:
          host: postgresql.database.svc.cluster.local
          port: 5432
          username: sub2api
          database: sub2api
          sslmode: disable
          existingSecret: sub2api-external-postgresql
          existingSecretPasswordKey: postgres-password
