apiVersion: v1
data:
  bookmarks.yaml: |
    - Workflows:
        - WeChat:
            - abbr: WeChat
              icon: sh-wechat
              href: https://mp.weixin.qq.com/
              description: Medium中文公众号
        - Toutiao:
            - abbr: Toutiao
              icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/toutiao.png
              href: https://www.toutiao.com/
              description: Apple内幕推送
    - Blog:
        - DEV-BLOG:
            - abbr: ay's dev blog
              icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/dev_blog.png
              href: https://aaronyang0628.github.io/docs/
        - WZ-BLOG:
            - abbr: wangzhi
              icon: blogger
              href: https://blog.geekcity.tech/articles/
        - BK-BLOG:
            - abbr: cnconti
              icon: blogger
              href: https://memo.cnconti.tech/#/
    - Developer:
        - Github:
            - abbr: GH
              icon: github
              href: https://github.com/AaronYang0628
        - Aliyun:
            - abbr: Ali
              icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/aliyun.png
              href: https://home.console.aliyun.com/home/dashboard/ProductAndService
        - OperatorHub:
            - abbr: OSH
              icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/operator_hub.png
              href: https://operatorhub.io/
        - Artifacthub:
            - abbr: AH
              icon: artifacthub
              href: https://artifacthub.io/
        - ACR:
            - abbr: ACR
              icon: docker-engine
              href: https://cr.console.aliyun.com/cn-hongkong/instance/dashboard
        - DD-Dev:
            - icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/dingding.png
              href: https://open-dev.dingtalk.com/
              description: https://open-dev.dingtalk.com/
        - DD-Admin:
            - icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/dingding.png
              href: https://oa.dingtalk.com
              description: https://oa.dingtalk.com
    - Tool:
        - ChatGPT:
            - abbr: chatgpt
              icon: chatgpt
              href: https://chatgpt.com/
        - Deepseek:
            - abbr: DB
              icon: deepseek
              href: https://platform.deepseek.com/
        - Gemini:
            - abbr: GM
              icon: google-gemini
              href: https://gemini.google.com/
        - Claude Code:
            - abbr: Claude
              icon: claude-ai
              href: https://claude.ai/new
        - FontAwesome:
            - abbr: FA
              icon: fontawesome
              href: https://fontawesome.com/v6/search?o=r
        - Skywork:
            - abbr: SKY
              icon: google-slides
              href: https://skywork.ai/
        - ICON:
            - abbr: IC
              icon: dashboard-icons-dark
              href: https://dashboardicons.com/
    - Media:
        - Twitter:
            - abbr: twitter
              icon: twitter
              href: https://x.com/
        - RedBook:
            - abbr: XHS
              icon: si-xiaohongshu
              href: https://www.xiaohongshu.com/explore
        - YouTube:
            - abbr: YT
              icon: youtube
              href: https://youtube.com/
        - Bilibili:
            - abbr: BB
              icon: bilibili
              href: https://bilibili.com/
        - IYF:
            - abbr: IYF
              icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/iyf.png
              href: https://www.iyf.tv/?from=1
        - WeChat:
            - abbr: WeChat
              icon: sh-wechat
              href: https://mp.weixin.qq.com/
        - Medium:
            - abbr: Medium
              icon: medium-dark
              href: https://medium.com/
  custom.css: |
    # test pre-commit hook
  custom.js: ""
  docker.yaml: ""
  kubernetes.yaml: |-
    mode: default
    ingress: true
  services.yaml: "- Cluster Management:\n    - Homepage:\n        icon: homepage\n
    \       href: http://home.72602.online\n        description: 72602 Cluster Dashboard\n
    \       namespace: monitor\n        app: homepage\n        showStats: true\n    -
    ArgoCD:\n        icon: argo-cd\n        description: GitOps Applications\n        href:
    https://argocd.72602.online\n        siteMonitor: https://argocd.72602.online\n
    \       namespace: argocd\n        app: argocd-server\n        showStats: true\n
    \       widget:\n          type: argocd\n          url: https://argocd.72602.online\n
    \         key: \"{{HOMEPAGE_VAR_ARGOCD_KEY}}\"\n          insecure: true\n    -
    Uptime Kuma:\n        icon: sh-uptime-kuma\n        href: https://uptime.72602.online\n
    \       description: Service Availability\n        siteMonitor: https://uptime.72602.online\n
    \       namespace: monitor\n        app: uptime-kuma\n        showStats: true\n
    \   - Ops Agent:\n        icon: terminal\n        href: https://ops.agent.72602.online\n
    \       description: Cluster Operations Agent\n        namespace: application\n
    \       app: ops-agent\n        showStats: true\n- Basic Services:\n    - SSH
    At 72602:\n        icon: terminal\n        description: SSH Service At 72602 Home\n
    \       widget:\n          type: uptimekuma\n          url: https://uptime.72602.online\n
    \         slug: 72602-minipc-ssh\n    - Clash At 72602:\n        icon: clash\n
    \       href: http://clash.72602.online/ui\n        description: http://clash.72602.online/ui\n
    \       siteMonitor: http://clash.72602.online/ui\n    - Clash At ECS:\n        icon:
    clash\n        href: http://47.110.67.161:56396/ui\n        description: http://47.110.67.161:56396\n
    \       siteMonitor: http://47.110.67.161:56396/ui\n    - Sub2API-WZ:\n        icon:
    https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/sub2api.png\n
    \       href: https://sub2api.home.geekcity.tech:32443\n        description: https://sub2api.home.geekcity.tech:32443\n
    \       siteMonitor: https://sub2api.home.geekcity.tech:32443\n    - Minio Ingress:\n
    \       icon: minio\n        href: https://console.minio.72602.online\n        description:
    https://console.minio.72602.online\n        siteMonitor: https://console.minio.72602.online\n-
    72602 Hosted:\n    - Sub2API-AY:\n        icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/sub2api.png\n
    \       href: https://sub2api.72602.online\n        description: https://sub2api.72602.online\n
    \       siteMonitor: https://sub2api.72602.online\n    - N8N Ingress:\n        icon:
    n8n\n        href: https://n8n.72602.online\n        description: https://n8n.72602.online\n
    \       siteMonitor: https://n8n.72602.online\n    - Port Blog Ingress:\n        href:
    http://ops.docs.72602.online\n        icon: hugo\n        description: http://ops.docs.72602.online\n
    \       siteMonitor: http://ops.docs.72602.online\n- External Links:\n    - ZJLAB
    Nanhu:\n        href: https://zjic.zhejianglab.com/portal/navigation\n        icon:
    https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/zjlab.png\n
    \       description: https://zjic.zhejianglab.com/portal/navigation\n        siteMonitor:
    https://zjic.zhejianglab.com/portal/navigation\n    - ZJLAB Haina:\n        href:
    https://open-sci-datahub.zero2x.org/home\n        icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/zjlab.png\n
    \       description: https://open-sci-datahub.zero2x.org/home\n        siteMonitor:
    https://open-sci-datahub.zero2x.org/home\n    - Browserless:\n        href: https://www.browserless.io/account/dashboard\n
    \       icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/browserless.png\n
    \       description: Browserless Dashboard\n         \n- Conatiners: []\n"
  settings.yaml: |-
    title: 72602 Homepage
    theme: gray
    description: A Monitoring Dashboard for All Services in 72602
    startUrl: /
    discovery:
      enabled: false
    hideVersion: true
    disableUpdateCheck: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
      provider: google
    layout:
      Developer:
        style: row
        columns: 5
      Blog:
        style: row
        columns: 5
      Workflows:
        style: row
        columns: 5
      Media:
        iconsOnly: true
      Tool:
        iconsOnly: true
  widgets.yaml: "- resources:\n    backend: resources\n    expanded: true\n    cpu:
    true\n    memory: true\n    network: default\n- kubernetes:\n    cluster:\n      show:
    true\n      cpu: true\n      memory: true\n      showLabel: true\n      label:
    72602 Cluster\n    nodes:\n      show: true\n      cpu: true\n      memory: true\n
    \     showLabel: true\n- search:\n    provider: google\n    target: _blank\n-
    logo:\n    href: http://home.72602.online\n    target: _blank \n    icon: https://raw.githubusercontent.com/AaronYang0628/docs/refs/heads/main/static/icons/port_icon.png\n"
kind: ConfigMap
metadata:
  name: homepage
