apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-data-pvc
  labels:
    app.kubernetes.io/name: portal-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
