apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-catalog-pvc
  labels:
    app: cosmos-catalog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
