FROM m.daocloud.io/docker.io/library/alpine:3.22

RUN apk add --no-cache autossh openssh-client \
    && addgroup -S -g 10001 autossh \
    && adduser -S -D -H -u 10001 -G autossh autossh

LABEL org.opencontainers.image.title="ZJLAB NewAPI reverse tunnel" \
      org.opencontainers.image.description="Non-root autossh client for the ZJLAB NewAPI reverse tunnel"

USER 10001:10001
ENTRYPOINT ["/usr/bin/autossh"]
