apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ops-agent
  namespace: application
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: ops.agent.72602.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ops-agent
                port:
                  name: http
  tls:
    - hosts:
        - ops.agent.72602.online
      secretName: ops.agent.72602.online-tls
